"""create_sample_test

Revision ID: 446fa7fed31b
Revises: 
Create Date: 2024-11-06 17:47:22.833992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '446fa7fed31b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_email'), 'documents', ['email'], unique=True)
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_index(op.f('ix_documents_name'), 'documents', ['name'], unique=False)
    op.create_table('document_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_pages_document_id'), 'document_pages', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_pages_id'), 'document_pages', ['id'], unique=False)
    op.create_table('document_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('line_idx', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('startIndex', sa.Integer(), nullable=True),
    sa.Column('endIndex', sa.Integer(), nullable=True),
    sa.Column('translation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['document_pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_lines_id'), 'document_lines', ['id'], unique=False)
    op.create_index(op.f('ix_document_lines_page_id'), 'document_lines', ['page_id'], unique=False)
    op.create_table('document_line_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('from_lang', sa.String(), nullable=True),
    sa.Column('to_lang', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('translation', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['document_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_line_translations_id'), 'document_line_translations', ['id'], unique=False)
    op.create_index(op.f('ix_document_line_translations_line_id'), 'document_line_translations', ['line_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_line_translations_line_id'), table_name='document_line_translations')
    op.drop_index(op.f('ix_document_line_translations_id'), table_name='document_line_translations')
    op.drop_table('document_line_translations')
    op.drop_index(op.f('ix_document_lines_page_id'), table_name='document_lines')
    op.drop_index(op.f('ix_document_lines_id'), table_name='document_lines')
    op.drop_table('document_lines')
    op.drop_index(op.f('ix_document_pages_id'), table_name='document_pages')
    op.drop_index(op.f('ix_document_pages_document_id'), table_name='document_pages')
    op.drop_table('document_pages')
    op.drop_index(op.f('ix_documents_name'), table_name='documents')
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_email'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
